#+BEGIN_COMMENT
.. title: How Do Machines Learn?
.. slug: how-do-machines-learn
.. date: 2018-10-17 12:13:54 UTC-07:00
.. tags: grokking,book notes,machine learning
.. category: Grokking
.. link: 
.. description: Notes on chapter two of "Grokking Machine Learning".
.. type: text

#+END_COMMENT
* What is this?
  I'm reading [[https://www.manning.com/books/grokking-deep-learning][Grokking Deep Learning]] and am going to put my notes here. This is from Chapter 2 - /How Do Machines Learn/?
* What is Deep Learning?
  Deep learning is a sub-field of /Machine Learning/ that primarily use /Artificial Neural Networks/.
* What is Machine Learning?
  Machine Learning is a sub-field of computer science where computers learn to do things that they weren't explicitly programmed to do. Their main goal is to map a data set to some other useful data set.
* What is Supervised Learning?
  Supervised Learning methods transforms one dataset into another. They take what we already know and try to come up with what we want to know.
* What is Unsupervised Learning?
  Unsupervised Learring methods group your data. They take your data and try to come up with labels for clusters within the data.
* What are Parametric and Non-Parametric Learning?
** What is Parametric Learning?
  - Parametric: trial-and-error (has a fixed number of parameters)
  - Non-Parametric: counting and probability (has an infinite number of parameters)
The classifications /Supervised/ and /Unsupervised/ refers to the pattern that is being learned, while /Parametric/ vs /Non-Parametric/ is about the way what's learned is stored.
*** What is Supervised Parametric Learning?
   Trial and error learning that tunes your model's knobs.
   - Step One: Make a prediction using your data
   - Step Two: Compare your predictions to the real answer
   - Step Three: Change your model based on how you did - make it more or less sensitive to each of the parameters
*** What is Unsupervised Parametric Learning?
   It's parametric, so it has knobs to twiddle when finding groups, but the knobs are used to tune the input data's likelihood of being in a group.
** What is Non-Parametric Learnining?
   These are counting-based methods - the number of parameters depends on the data. If you have a set of labels relating to an outcome, each label might be a parameter and your model would count how many times each label lead to the outcome you're watching.
