#+BEGIN_COMMENT
.. title: Dermatologist Mini-Project
.. slug: dermatologist-mini-project
.. date: 2019-01-16 21:17:45 UTC-08:00
.. tags: project,dermatologist,cnn,transfer learning
.. category: Project
.. link: 
.. description: Replicating the melanoma-detection CNN project.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 1
* Introduction
  This is an exercise in using transfer learning to diagnose melanoma based on images of skin legions. There are three diseases to be detected:
  - Melanoma
  - Nevus
  - Sebhorrheic Keratosis

There is a paper online [[https://arxiv.org/pdf/1710.05006.pdf][here]] (PDF link) that describes the approaches that did best in the competition.
* Data Sources
  The data is taken from the [[https://challenge.kitware.com/#challenge/583f126bcad3a51cc66c8d9a][ISIC 2017: Skin Lesion Analysis Towards Melanoma Detection]] challenge. 
  - [[https://s3-us-west-1.amazonaws.com/udacity-dlnfd/datasets/skin-cancer/train.zip][Training Data]]
  - [[https://s3-us-west-1.amazonaws.com/udacity-dlnfd/datasets/skin-cancer/valid.zip][Validation Data]]
  - [[https://s3-us-west-1.amazonaws.com/udacity-dlnfd/datasets/skin-cancer/test.zip][Test Data]]

Each folder contains three sub-folders:
 - =melanoma/=
 - =nevus/=
 - =seborrheic_keratosis/=

* Set Up
** Imports
*** Python
#+BEGIN_SRC ipython :session dermatologoist :results none
from pathlib import Path
import os
#+END_SRC
*** PyPi
#+BEGIN_SRC ipython :session dermatologoist :results none
from dotenv import load_dotenv
from torchvision import datasets
import torch
import torchvision.models as models
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optimizer
import torchvision.transforms as transforms
#+END_SRC
*** This Project
#+BEGIN_SRC ipython :session dermatologoist :results none
from neurotic.tangles.timer import Timer
#+END_SRC
** Loading the Data
#+BEGIN_SRC ipython :session dermatologoist :results none
load_dotenv()
train_path = Path(os.environ.get("TRAIN")).expanduser()
test_path = Path(os.environ.get("TEST")).expanduser()
validate_path = Path(os.environ.get("VALIDATE")).expanduser()

assert train_path.is_dir()
assert test_path.is_dir()
assert validate_path.is_dir()
#+END_SRC

* References
  - [[https://github.com/udacity/dermatologist-ai][Github Repository]]


