#+BEGIN_COMMENT
.. title: Named Entity Recognition
.. slug: named-entity-recognition
.. date: 2021-01-13 14:55:54 UTC-08:00
.. tags: lstm,rnn,nlp,ner
.. category: NLP
.. link: 
.. description: Named Entity Recognition with RNNs.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-9974ba11-9b71-4b8e-8dc9-4b5779900b41-ssh.json
#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* Named Entity Recognition (NER)
We'll start with the question - "What is Named Entity Recognition (NER)?". NER is a subtask of information extraction that locates and classifies named entities in a text. The named entities could be organizations, persons, locations, times, etc. 

We'll train a named entity recognition system that could be trained in a few seconds (on a GPU) and will get around 75% accuracy. Then we'll load in the exact version of the model, which was trained for a longer period of time. We can then evaluate the trained version of the model to get 96% accuracy! Finally, we'll test the named entity recognition system with new sentences.

** The Posts In Order
   These are the posts where we'll actually implement the code.
   
  - {{% lancelot title="Preprocessing The Data" %}}ner-pre-processing-the-data{{% /lancelot %}}  
  - {{% lancelot title="Generating the Data" %}}ner-data{{% /lancelot %}}
  - {{% lancelot title="Building the Model" %}}ner-building-the-model{{% /lancelot %}}
  - {{% lancelot title="Training the Model" %}}ner-training-the-model{{% /lancelot %}}    
  - {{% lancelot title="Evaluating the Model" %}}ner-evaluating-the-model{{% /lancelot %}}
  - {{% lancelot title="Testing the Model" %}}ner-testing-the-model{{% /lancelot %}}   
