#+BEGIN_COMMENT
.. title: Tips, Tricks and Other Notes
.. slug: tips-tricks-and-other-notes
.. date: 2018-11-25 14:13:27 UTC-08:00
.. tags: pytorch,lecture,notes
.. category: PyTorch
.. link: 
.. description: Final notes from the introduction to pytorch section.
.. type: text
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 1
* On Shapes
  As the tensors go through the model you should check the shapes to make sure they are correct (or at least what you expect).
* Troubleshooting Training
  - Make sure you are clearing the gradients in the training loop with =optimizer.zero_grad()=
  - In the validation loop, set the network to evaluation mode with =model.eval()= and then back to training mode with =model.train=
* CUDA Problems
  If you see an error saying pytorch =Expected an object of type torch.FloatTensor but found type torch.cuda.FloatTensor= then it means something is trying to be run on the CPU but something else wants to use the GPU. Make sure you called =.to(device)= on the model and all your tensors (including the data).
