#+BEGIN_COMMENT
.. title: Setting up pytest
.. slug: setting-up-pytest
.. date: 2023-07-02 15:28:13 UTC-07:00
.. tags: testing,pytest
.. category: Testing
.. link: 
.. description: Setting up pytest testing.
.. type: text

#+END_COMMENT
#+TOC: headlines 2

* What is this about?

 This is a post to generate and document the ~pytest.ini~ configuration for testing.

* Requirements
** The Neurotic Repository

To make the neurotic code importable you need to install the package (in development mode, since it's (hopefully) always changing) using [[https://pip.pypa.io/en/stable/][pip]].

#+begin_src fish
pip install --editable .
#+end_src

* The Testing Dependencies

There are some things that need to be installed to get the code to run (like numpy and nltk) but for the testing this is what's needed.

#+begin_src python :tangle ../tests/testing-requirements
expects
faker
pytest
pytest-bdd
pytest-mock
pytest-xdist
#+end_src

This list is in a text-file (~tests/testing-requriements~) so they can be installed by changing into the ~tests~ folder and running pip.

#+begin_src fish
pip install --requirement testing-requirements
#+end_src

* The Configuration File

Pytest can read in an [[https://en.wikipedia.org/wiki/INI_file?useskin=vector][INI]] formatted file. It has a bunch of [[https://docs.pytest.org/en/7.1.x/reference/reference.html#ini-options-ref][configuration options]] but I haven't really explored them much. I mostly use it to set the command line arguments that I would otherwise pass in.

#+begin_src ini :tangle ../tests/pytest.ini :exports none
<<default>>

<<run-once>>
<<debugger>>
#+end_src

** The Regular Testing Run
#+begin_src ini :noweb-ref default
[pytest]
addopts = --exitfirst --failed-first --color yes --gherkin-terminal-reporter
          --looponfail --numprocesses auto
#+end_src

I didn't realize it before, but as [[https://stackoverflow.com/a/11401142][this stackoverflow answer]] mentions, you can break up long line in INI files (assuming that the code is using python's ConfigParser) by indenting the continuation lines (although it appears, unfortunately, to break [[https://pygments.org/][pygments']] syntax highlighting).

Here's a breakdown of the options.

- ~exitfirst~: stop testing after the first failed test
- ~failed-first~: when re-starting the tests, start with the test that failed
- ~color yes~: Add some highlight-coloring to the pytest output
- ~gherkin-terminal-reporter~: Format the output using pytest-bdd
- ~looponfail~: re-run the testing if a file changes
- ~numprocesses auto~: Run the tests in parallel across all available cores.

The ~numprocesses~ option can alternatively take ~logical~ as an argument, meaning use all logical CPUs, not physical cores (this requires you install ~pytest-xdist[psutil]~) or the actual number of processes you want to run in parallel.

** The Run-Once
This removes the automatic re-running of tests. I don't really use this, but sometimes it can be helpful, especially when using something like Selenium that slows everything down a lot, to not re-run the test every time you save a file.

#+begin_src ini :noweb-ref run-once
# addopts = --exitfirst --failed-first --color yes --gherkin-terminal-reporter --numprocesses auto
#+end_src

** The PUDB Run

~pytest~ will grab standard out by default, making it impossible to run an interactive debugger. They have support for python's [[https://docs.python.org/3/library/pdb.html][pdb]] debugger, but I use [[https://documen.tician.de/pudb/][pudb]] instead, so this set of arguments turns off the capturing of standard out which will let you run the tests with PUDB. There is [[https://github.com/wronglink/pytest-pudb][a project]] that integrates ~pudb~ into pytest, but it appears to have died out, so I'll just stick to my old way of doing it.

#+begin_src ini :noweb-ref debugger
# addopts = --exitfirst --failed-first --color yes --gherkin-terminal-reporter --capture=no
#+end_src
* Links

- Faker 18.11.2 documentation [Internet]. [cited 2023 Jul 2]. Available from: https://faker.readthedocs.io/en/master/index.html
- INI file. In: Wikipedia [Internet]. 2023 [cited 2023 Jul 2]. Available from: https://en.wikipedia.org/w/index.php?title=INI_file&oldid=1153411356
- Pytest-BDD 6.1.1 documentation [Internet]. [cited 2023 Jul 2]. Available from: https://pytest-bdd.readthedocs.io/en/latest/#bdd-library-for-the-pytest-runner
- pip documentation v23.1.2 [Internet]. [cited 2023 Jul 2]. Available from: https://pip.pypa.io/en/stable/
- pudb 2022.1.3 documentation [Internet]. [cited 2023 Jul 2]. Available from: https://documen.tician.de/pudb/
- pytest-mock documentation [Internet]. [cited 2023 Jul 2]. Available from: https://pytest-mock.readthedocs.io/en/latest/
- pytest-xdist — pytest-xdist documentation [Internet]. [cited 2023 Jul 2]. Available from: https://pytest-xdist.readthedocs.io/en/stable/
