#+BEGIN_COMMENT
.. title: Locality-Sensitive Hashing (LSH) for Machine Translation
.. slug: machine-translation-with-locality-sensitive-hashing
.. date: 2020-10-22 17:43:58 UTC-07:00
.. tags: nlp,machine translation,assignment
.. category: NLP
.. link: 
.. description: Implementing Locality Sensitive Hashing for the English to French Translation
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-62e03387-23bf-4675-96a8-2b918ac0854c-ssh.json

#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* Beginning
  This is a continuation of the post in which we implemented {{% lancelot title="k-Nearest Neighbors" %}}machine-translation-k-nearest-neighbors{{% /lancelot %}}. It's part of a series of posts on building an English to French translator whose links are gathered in the {{% lancelot title="this post" %}}machine-translation{{% /lancelot %}}.
* Middle
** 3. Locality-Sensitive Hashing (LSH) and Document Search

In this part of the assignment, you will implement a more efficient version of k-nearest neighbors using locality sensitive hashing. You will then apply this to document search.
 
 - Process the tweets and represent each tweet as a vector (represent a document with a vector embedding).
 - Use locality sensitive hashing and k nearest neighbors to find tweets that are similar to a given tweet.

#+begin_src python :results none
# get the positive and negative tweets
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')
all_tweets = all_positive_tweets + all_negative_tweets
#+end_src

*** 3.1 Getting the document embeddings

**** Bag-of-words (BOW) document models
 Text documents are sequences of words.
  - The ordering of words makes a difference. For example, sentences "Apple pie is better than pepperoni pizza." and "Pepperoni pizza is better than apple pie" have opposite meanings due to the word ordering.
  - However, for some applications, ignoring the order of words can allow us to train an efficient and still effective model.
  - This approach is called Bag-of-words document model.

*** Document embeddings
    - /Document embedding/ is created by summing up the embeddings of all words in the document.
    - If we don't know the embedding of some word, we can ignore that word.

 **Exercise 07**:
 Complete the =get_document_embedding()= function.
  - The function =get_document_embedding()= encodes entire document as a "document" embedding.
  - It takes in a docoument (as a string) and a dictionary, =en_embeddings=
  - It processes the document, and looks up the corresponding embedding of each word.
   - It then sums them up and returns the sum of all word vectors of that processed tweet.

**** Hints
 - You can handle missing words easier by using the =get()= method of the python dictionary instead of the bracket notation (i.e. "[ ]"). See more about it [[https://stackoverflow.com/a/11041421/12816433"][here]]
 - The default value for missing word should be the zero vector. Numpy will [[https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html][broadcast]] simple 0 scalar into a vector of zeros during the summation.
 - Alternatively, skip the addition if a word is not in the dictonary.
 - You can use your =process_tweet()= function which allows you to process the tweet. The function just takes in a tweet and returns a list of words.

#+begin_src python :results none
# UNQ_C12 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def get_document_embedding(tweet, en_embeddings): 
    '''
    Input:
        - tweet: a string
        - en_embeddings: a dictionary of word embeddings
    Output:
        - doc_embedding: sum of all word embeddings in the tweet
    '''
    doc_embedding = np.zeros(300)

    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    # process the document into a list of words (process the tweet)
    processed_doc = None
    for word in processed_doc:
        # add the word embedding to the running total for the document embedding
        doc_embedding = None
    ### END CODE HERE ###
    return doc_embedding
#+end_src

You do not have to input any code in this cell, but it is relevant to grading, so please do not change anything

#+begin_src python :results output :exports both
# testing your function
custom_tweet = "RT @Twitter @chapagain Hello There! Have a great day. :) #good #morning http://chapagain.com.np"
tweet_embedding = get_document_embedding(custom_tweet, en_embeddings_subset)
tweet_embedding[-5:]
#+end_src

 **Expected output**:
 
#+RESULTS
 array([-0.00268555, -0.15378189, -0.55761719, -0.07216644, -0.32263184])

*** Exercise 08

**** Store all document vectors into a dictionary
 Now, let's store all the tweet embeddings into a dictionary. Implement =get_document_vecs()=.


#+begin_src python :results none
def get_document_vecs(all_docs, en_embeddings):
    '''
    Input:
        - all_docs: list of strings - all tweets in our dataset.
        - en_embeddings: dictionary with words as the keys and their embeddings as the values.
    Output:
        - document_vec_matrix: matrix of tweet embeddings.
        - ind2Doc_dict: dictionary with indices of tweets in vecs as keys and their embeddings as the values.
    '''

    # the dictionary's key is an index (integer) that identifies a specific tweet
    # the value is the document embedding for that document
    ind2Doc_dict = {}

    # this is list that will store the document vectors
    document_vec_l = []

    for i, doc in enumerate(all_docs):

        ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
        # get the document embedding of the tweet
        doc_embedding = None

        # save the document embedding into the ind2Tweet dictionary at index i
        ind2Doc_dict[i] = None

        # append the document embedding to the list of document vectors
        document_vec_l.append(None)

        ### END CODE HERE ###

    # convert the list of document vectors into a 2D array (each row is a document vector)
    document_vec_matrix = np.vstack(document_vec_l)

    return document_vec_matrix, ind2Doc_dict
#+end_src

#+begin_src python :results none
document_vecs, ind2Tweet = get_document_vecs(all_tweets, en_embeddings_subset)
#+end_src

#+begin_src python :results output :exprts both
print(f"length of dictionary {len(ind2Tweet)}")
print(f"shape of document_vecs {document_vecs.shape}")
#+end_src

 Expected Output

#+begin_example
 length of dictionary 10000
 shape of document_vecs (10000, 300)
#+end_example
*** 3.2 Looking up the tweets

 Now you have a vector of dimension (m,d) where =m= is the number of tweets (10,000) and =d= is the dimension of the embeddings (300).  Now you will input a tweet, and use cosine similarity to see which tweet in our corpus is similar to your tweet.

#+begin_src python :results none
my_tweet = 'i am sad'
process_tweet(my_tweet)
tweet_embedding = get_document_embedding(my_tweet, en_embeddings_subset)
#+end_src

This gives you a tweet similar to your input.

#+begin_src python :results output :exprts both
idx = np.argmax(cosine_similarity(document_vecs, tweet_embedding))
print(all_tweets[idx])
#+end_src

 Expected Output

#+begin_example
@zoeeylim sad sad sad kid :( it's ok I help you watch the match HAHAHAHAHA
#+end_example
*** 3.3 Finding the most similar tweets with LSH

 You will now implement locality sensitive hashing (LSH) to identify the most similar tweet. Instead of looking at all 10,000 vectors, you can just search a subset to find its nearest neighbors.

Let's say you have a set of data points,  You can divide the vector space into regions and search within one region for nearest neighbors of a given vector.

#+begin_src python :results output :exprts both
N_VECS = len(all_tweets)       # This many vectors.
N_DIMS = len(ind2Tweet[1])     # Vector dimensionality.
print(f"Number of vectors is {N_VECS} and each has {N_DIMS} dimensions.")
#+end_src

*** Choosing the number of planes
 
   -  Each plane divides the space to /2/ parts.
   -  So /n/ planes divide the space into \(2^{n}\) hash buckets.
   -  We want to organize 10,000 document vectors into buckets so that every bucket has about /~16/ vectors.
   -  For that we need \(\frac{10000}{16}=625\) buckets.
   -  We're interested in /n/, number of planes, so that \(2^{n}= 625\). Now, we can calculate \(n=\log_{2}625 = 9.29 \approx 10\).

The number of planes. We use \(\log_2(625)\) to have ~16 vectors/bucket.

#+begin_src python :results none
N_PLANES = 10
#+end_src

 Number of times to repeat the hashing to improve the search.

#+begin_src python :results none
N_UNIVERSES = 25
#+end_src
*** 3.4 Getting the hash number for a vector

For each vector, we need to get a unique number associated to that vector in order to assign it to a "hash bucket".

*** Hyperlanes in vector spaces
   - In /3/-dimensional vector space, the hyperplane is a regular plane. In /2/ dimensional vector space, the hyperplane is a line.
   - Generally, the hyperplane is subspace which has dimension /1/ lower than the original vector space has.
   - A hyperplane is uniquely defined by its normal vector.
   - Normal vector /n/ of the plane \(\pi\) is the vector to which all vectors in the plane \(\pi\) are orthogonal (perpendicular in /3/ dimensional case).

*** Using Hyperplanes to split the vector space
 We can use a hyperplane to split the vector space into /2/ parts.
 - All vectors whose dot product with a plane's normal vector is positive are on one side of the plane.
 - All vectors whose dot product with the plane's normal vector is negative are on the other side of the plane.

*** Encoding hash buckets
   - For a vector, we can take its dot product with all the planes, then encode this information to assign the vector to a single hash bucket.
   - When the vector is pointing to the opposite side of the hyperplane than normal, encode it by 0.
   - Otherwise, if the vector is on the same side as the normal vector, encode it by 1.
   - If you calculate the dot product with each plane in the same order for every vector, you've encoded each vector's unique hash ID as a binary number, like [0, 1, 1, ... 0].

*** Exercise 09: Implementing hash buckets

 We've initialized hash table =hashes= for you. It is list of =N_UNIVERSES= matrices, each describes its own hash table. Each matrix has =N_DIMS= rows and =N_PLANES= columns. Every column of that matrix is a =N_DIMS=-dimensional normal vector for each of =N_PLANES= hyperplanes which are used for creating buckets of the particular hash table.

 *Exercise*: Your task is to complete the function =hash_value_of_vector= which places vector =v= in the correct hash bucket.

 - First multiply your vector $v$, with a corresponding plane. This will give you a vector of dimension \((1,\text{N_planes})\).
 - You will then convert every element in that vector to 0 or 1.
 - You create a hash vector by doing the following: if the element is negative, it becomes a 0, otherwise you change it to a 1.
 - You then compute the unique number for the vector by iterating over =N_PLANES=
 - Then you multiply \(2^i\) times the corresponding bit (0 or 1).
 - You will then store that sum in the variable =hash_value=.

 **Intructions:** Create a hash for the vector in the function below.
 Use this formula:

\[
 hash = \sum_{i=0}^{N-1} \left( 2^{i} \times h_{i} \right)
\]

**** Create the sets of planes
     - Create multiple (25) sets of planes (the planes that divide up the region).
     - You can think of these as 25 separate ways of dividing up the vector space with a different set of planes.
     - Each element of this list contains a matrix with 300 rows (the word vector have 300 dimensions), and 10 columns (there are 10 planes in each "universe").

#+begin_src python :results none
np.random.seed(0)
planes_l = [np.random.normal(size=(N_DIMS, N_PLANES))
            for _ in range(N_UNIVERSES)]
#+end_src

***** Hints

      - =numpy.squeeze()= removes unused dimensions from an array; for instance, it converts a (10,1) 2D array into a (10,) 1D array

#+begin_src python :results none
# UNQ_C17 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def hash_value_of_vector(v, planes):
    """Create a hash for a vector; hash_id says which random hash to use.
    Input:
        - v:  vector of tweet. It's dimension is (1, N_DIMS)
        - planes: matrix of dimension (N_DIMS, N_PLANES) - the set of planes that divide up the region
    Output:
        - res: a number which is used as a hash for your vector

    """
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    # for the set of planes,
    # calculate the dot product between the vector and the matrix containing the planes
    # remember that planes has shape (300, 10)
    # The dot product will have the shape (1,10)
    dot_product = None

    # get the sign of the dot product (1,10) shaped vector
    sign_of_dot_product = None

    # set h to be false (eqivalent to 0 when used in operations) if the sign is negative,
    # and true (equivalent to 1) if the sign is positive (1,10) shaped vector
    h = None

    # remove extra un-used dimensions (convert this from a 2D to a 1D array)
    h = None

    # initialize the hash value to 0
    hash_value = 0

    n_planes = planes.shape[1]
    for i in range(n_planes):
        # increment the hash value by 2^i * h_i
        hash_value += None
    ### END CODE HERE ###

    # cast hash_value as an integer
    hash_value = int(hash_value)

    return hash_value
#+end_src

#+begin_src python :results output :exprts both
np.random.seed(0)
idx = 0
planes = planes_l[idx]  # get one 'universe' of planes to test the function
vec = np.random.rand(1, 300)
print(f" The hash value for this vector,",
      f"and the set of planes at index {idx},",
      f"is {hash_value_of_vector(vec, planes)}")
#+end_src

 Expected Output

#+begin_example
# The hash value for this vector, and the set of planes at index 0, is 768
#+end_example
*** 3.5 Creating a hash table
*** Exercise 10

 Given that you have a unique number for each vector (or tweet), You now want to create a hash table. You need a hash table, so that given a hash_id, you can quickly look up the corresponding vectors. This allows you to reduce your search by a significant amount of time.

 We have given you the =make_hash_table= function, which maps the tweet vectors to a bucket and stores the vector there. It returns the =hash_table= and the =id_table=. The =id_table= allows you know which vector in a certain bucket corresponds to what tweet.

**** Hints
     - a dictionary comprehension, similar to a list comprehension, looks like this: `{i:0 for i in range(10)}`, where the key is 'i' and the value is zero for all key-value pairs. 

#+begin_src python :results none
def make_hash_table(vecs, planes):
    """
    Input:
        - vecs: list of vectors to be hashed.
        - planes: the matrix of planes in a single "universe", with shape (embedding dimensions, number of planes).
    Output:
        - hash_table: dictionary - keys are hashes, values are lists of vectors (hash buckets)
        - id_table: dictionary - keys are hashes, values are list of vectors id's
                            (it's used to know which tweet corresponds to the hashed vector)
    """
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###

    # number of planes is the number of columns in the planes matrix
    num_of_planes = None

    # number of buckets is 2^(number of planes)
    num_buckets = None

    # create the hash table as a dictionary.
    # Keys are integers (0,1,2.. number of buckets)
    # Values are empty lists
    hash_table = None

    # create the id table as a dictionary.
    # Keys are integers (0,1,2... number of buckets)
    # Values are empty lists
    id_table = None

    # for each vector in 'vecs'
    for i, v in enumerate(vecs):
        # calculate the hash value for the vector
        h = None

        # store the vector into hash_table at key h,
        # by appending the vector v to the list at key h
        None

        # store the vector's index 'i' (each document is given a unique integer 0,1,2...)
        # the key is the h, and the 'i' is appended to the list at key h
        None

    ### END CODE HERE ###

    return hash_table, id_table
#+end_src


#+begin_src python :results output :exprts both
np.random.seed(0)
planes = planes_l[0]  # get one 'universe' of planes to test the function
vec = np.random.rand(1, 300)
tmp_hash_table, tmp_id_table = make_hash_table(document_vecs, planes)

print(f"The hash table at key 0 has {len(tmp_hash_table[0])} document vectors")
print(f"The id table at key 0 has {len(tmp_id_table[0])}")
print(f"The first 5 document indices stored at key 0 of are {tmp_id_table[0][0:5]}")
#+end_src

Expected output

#+RESULTS
 The hash table at key 0 has 3 document vectors
 The id table at key 0 has 3
 The first 5 document indices stored at key 0 of are [3276, 3281, 3282]


# <a name="3-6"></a>
# 
*** 3.6 Creating all hash tables

You can now hash your vectors and store them in a hash table that would allow you to quickly look up and search for similar vectors. Run the cell below to create the hashes. By doing so, you end up having several tables which have all the vectors. Given a vector, you then identify the buckets in all the tables.  You can then iterate over the buckets and consider much fewer vectors. The more buckets you use, the
 more accurate your lookup will be, but also the longer it will take.

**** Creating the hashtables
#+begin_src python :results output :exprts both
hash_tables = []
id_tables = []
for universe_id in range(N_UNIVERSES):  # there are 25 hashes
    print('working on hash universe #:', universe_id)
    planes = planes_l[universe_id]
    hash_table, id_table = make_hash_table(document_vecs, planes)
    hash_tables.append(hash_table)
    id_tables.append(id_table)
#+end_src
* End
  The next step is to use this to implement {{% lancelot title="approximate k-Nearest Neighbors" %}}machine-translation-with-approximate-knn{{% /lancelot %}} to compelete our application.
