#+BEGIN_COMMENT
.. title: Neural Machine Translation
.. slug: neural-machine-translation
.. date: 2021-02-11 19:56:46 UTC-08:00
.. tags: nlp,machine translation
.. category: NLP
.. link: 
.. description: An Attention Model for Machine Translation.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-95fb7f72-2980-4eed-b335-9f9a6c7ffbd5-ssh.json
#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* Neural Machine Translations
Here, we will build an English-to-German neural machine translation (NMT) model using Long Short-Term Memory (LSTM) networks with attention.  Machine translation is an important task in natural language processing and could be useful not only for translating one language to another but also for word sense disambiguation (e.g. determining whether the word "bank" refers to the financial bank, or the land alongside a river). Implementing this using just a Recurrent Neural Network (RNN) with LSTMs can work for short to medium length sentences but can result in vanishing gradients for very long sequences. To solve this, we will be adding an attention mechanism to allow the decoder to access all relevant parts of the input sentence regardless of its length. By completing this assignment, we will:  

 - learn how to preprocess your training and evaluation data
 - implement an encoder-decoder system with attention
 - understand how attention works
 - build the NMT model from scratch using Trax
 - generate translations using greedy and Minimum Bayes Risk (MBR) decoding

* The Posts
  This will be broken up into the following posts.

  - {{% lancelot title="The Data" %}}neural-machine-translation-the-data{{% /lancelot %}}
  - {{% lancelot title="Helper Functions" %}}neural-machine-translation-helper-functions{{% /lancelot %}}
  - {{% lancelot title="The Attention Model" %}}neural-machine-translation-the-attention-model{{% /lancelot %}}
  - {{% lancelot title="Training the Model" %}}neural-machine-translation-training-the-model{{% /lancelot %}}
  - {{% lancelot title="Testing the Model" %}}neural-machine-translation-testing-the-model{{% /lancelot %}}

First - a {{% lancelot title="look at the data" %}}neural-machine-translation-the-data{{% /lancelot %}}.
