#+BEGIN_COMMENT
.. title: Tweet Sentiment With Logistic Regression
.. slug: tweet-sentiment-with-logistic-regression
.. date: 2020-07-30 17:34:41 UTC-07:00
.. tags: nlp,twitter,sentiment analysis,logistic regression
.. category: NLP
.. link: 
.. description: An introduction to the Twitter Sentiment with Linear Regression.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

* Beginning
This is the first in a series of posts that will look at creating a Logistic Regression model to classify text by their polarity (positive or negative). The twitter platform is a social microblogging service that allows users to create /tweets/ of 280 characters or less and to include images in them. We are going to use Sentiment Analysis to decide whether a tweet is positive or negative in its sentiment.

* Sentiment Analysis
  Depending on which source you use, /Sentiment Analysis/ can be synonymous with /Opinion Mining/ or a part of Opinion Mining. So, to start - what's an opinion? An opinion is a subjective statement about what a person believes or thinks about something. It has five parts, the first three required to understand the opinion and the last two to add meaning to it {{% lancelot title="(Zhai & Massung, 2016)" %}}text-data-management-and-analysis{{% /lancelot %}}:

 1. The opinion holder (the person expressing the opinion)
 2. The opinion target (the subject of the person's opinion)
 3. The content of the opinion
 4. The context of the opinion
 5. The sentiment of the opinion

Sentiment Analysis is a part of Natural Language Processing that seeks to take free-form text and transform it into structured data that can then be used to analyze the text. With regards to part 5 - the sentiment of the opinion, in this case it refers to the polarity of the text - is it possitive in its feeling or negative? {{% lancelot title="(Pozzi et al., 2017)" %}}sentiment-analysis-in-social-networks{{% /lancelot %}}.

In this case we are going to focus on how to build the model using the sentiment, but it should be noted that without the first four parts of the opinion, the sentiment isn't really meaningful.
* Logistic Regression
